import type { Metadata } from "next";
import Link from "next/link";
import { CtaBand, PageHero } from "@/components/site/ui";
import { examples, overview } from "@/lib/data";
import { analyzeReview } from "@/lib/engine/analyze";
import { SITE } from "@/lib/site";

export const metadata: Metadata = {
  title: "Documentation",
  description: "The /api/analyze endpoint, risk tiers, thresholds, data files and how to run and test HomeLens AI locally.",
};

const TOC = [
  ["overview", "Overview"],
  ["analyze", "POST /api/analyze"],
  ["response", "Response"],
  ["tiers", "Risk tiers"],
  ["data", "Data files"],
  ["run", "Run locally"],
  ["test", "Testing"],
] as const;

export default function DocsPage() {
  const r = analyzeReview(examples[0].text);
  const sample = {
    model: r.model,
    risk_probability: r.risk_probability,
    operating_threshold: r.operating_threshold,
    management_attention: r.management_attention,
    primary_aspect: r.primary_aspect,
    detected_aspects: r.detected_aspects,
    evidence: r.evidence,
    recommended_action: r.recommended_action,
    "…": "sentences[], weights, matched_phrases, masking_applied, disclaimer",
  };
  const origin = SITE.url;
  return (
    <>
      <PageHero eyebrow="Documentation" title="Build on the analysis." lead="HomeLens AI is one Next.js app. The website, the demo and the analysis endpoint ship together, with no separate backend." />
      <div className="section tight">
        <div className="container docs-layout">
          <nav className="docs-toc" aria-label="On this page">
            {TOC.map(([id, label]) => (
              <a key={id} href={`#${id}`}>
                {label}
              </a>
            ))}
          </nav>
          <div className="docs-body">
            <section id="overview">
              <h2>Overview</h2>
              <p>The app ships Rithik’s anonymized artifacts as static JSON and runs a TypeScript port of his masking rules, complaint-phrase dictionary and TF–IDF logistic-regression model inside a route handler. A parity test checks the port against the Python model’s outputs.</p>
            </section>

            <section id="analyze">
              <h2>POST /api/analyze</h2>
              <p>Scores one review. Send JSON with a <code>text</code> string of 3–5,000 characters. Anything else returns <code>400</code>.</p>
              <pre className="codeblock">
                <span className="c"># request</span>
                {`\ncurl -s -X POST ${origin}/api/analyze \\\n  -H 'content-type: application/json' \\\n  -d '{"text":"They never showed up and overcharged me."}'`}
              </pre>
            </section>

            <section id="response">
              <h2>Response</h2>
              <p>The actual response for the first demo example, trimmed. <code>management_attention</code> is true when the review risk meets the operating threshold; it is <code>null</code> when the model is unavailable and only dictionary signals remain.</p>
              <pre className="codeblock">{JSON.stringify(sample, null, 2)}</pre>
            </section>

            <section id="tiers">
              <h2>Risk tiers</h2>
              <p>Provider tiers are relative to this corpus. They rank providers; they are not probabilities of any outcome.</p>
              <pre className="codeblock">{Object.entries(overview.tier_rules).map(([t, rule]) => `${t.padEnd(13)} ${rule}  (${overview.tiers[t as keyof typeof overview.tiers]} providers)`).join("\n")}</pre>
            </section>

            <section id="data">
              <h2>Data files</h2>
              <p>Generated by <code>scripts/export_frontend_data.py</code> from <code>artifacts/</code> and <code>app/risk_logic.py</code>. Never edit them by hand; CI fails if they are stale.</p>
              <pre className="codeblock">{`frontend/data/providers.json   anonymized provider scores, tiers, yearly history
frontend/data/aspects.json     8 aspects: lift, frequency, keywords, actions
frontend/data/overview.json    KPIs, tier counts, service groups, model metrics
frontend/data/facts.json       validated notebook facts (corpus size, splits)
frontend/data/risk_config.json masking rules and phrase dictionary
frontend/data/tfidf_model.json TF–IDF vocabulary, IDF and coefficients`}</pre>
            </section>

            <section id="run">
              <h2>Run locally</h2>
              <pre className="codeblock">{`cd frontend
npm install
npm run dev        # http://localhost:3000
npm run build && npm start`}</pre>
              <p>Optional environment variables: <code>NEXT_PUBLIC_CONTACT_EMAIL</code>, <code>NEXT_PUBLIC_REPO_URL</code>, <code>NEXT_PUBLIC_SITE_URL</code>. None are required.</p>
              {SITE.repoUrl && (
                <p>
                  Source: <a href={SITE.repoUrl}>{SITE.repoUrl}</a>
                </p>
              )}
            </section>

            <section id="test">
              <h2>Testing</h2>
              <pre className="codeblock">{`npm test           # 14 parity tests vs data/golden.json (Python outputs)
npm run typecheck`}</pre>
              <p>Refresh the data after rebuilding artifacts: <code>python scripts/build_artifacts.py &amp;&amp; python scripts/export_frontend_data.py</code>.</p>
              <p>
                Responsible-use notes are on the <Link href="/security">Responsible AI page</Link>.
              </p>
            </section>
          </div>
        </div>
      </div>
      <CtaBand title="Try the endpoint in the browser." primary={{ href: "/#try", label: "Open the analyzer" }} secondary={{ href: "/demo", label: "Live demo" }} />
    </>
  );
}
